ALTER TABLE restaurants
    DROP CONSTRAINT restaurants_pkey;

ALTER TABLE restaurants
    RENAME COLUMN id TO public_id;

ALTER TABLE restaurants
    ALTER COLUMN public_id DROP DEFAULT;

ALTER TABLE restaurants
    ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE restaurants
    ADD CONSTRAINT restaurants_pkey PRIMARY KEY (id);

ALTER TABLE restaurants
    ADD CONSTRAINT uk_restaurants_public_id UNIQUE (public_id);
